#!/usr/bin/env ts-node

const { writeFileSync, existsSync } = require('fs');
const { join } = require('path');
const { config } = require('dotenv');

// Load .env.local if it exists
const envLocalPath = join(__dirname, '..', '.env.local');
if (existsSync(envLocalPath)) {
  config({ path: envLocalPath });
}

// Get environment variables
const supabaseUrl = process.env['NG_APP_SUPABASE_URL'] || process.env['SUPABASE_URL'] || '';
const supabaseAnonKey = process.env['NG_APP_SUPABASE_ANON_KEY'] || process.env['SUPABASE_ANON_KEY'] || '';
const requiresBetaAccess = process.env['NG_APP_REQUIRES_BETA_ACCESS'] === 'true' || process.env['NG_APP_REQUIRES_BETA_ACCESS'] === undefined;
const betaAccessCodeHash = process.env['NG_APP_BETA_ACCESS_CODE_HASH'] || process.env['BETA_ACCESS_CODE_HASH'] || '';

// Generate development environment file
const devEnvContent = `// This file is auto-generated by scripts/generate-env.ts
// Do not edit manually - your changes will be overwritten
export const environment = {
  production: false,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  requiresBetaAccess: ${requiresBetaAccess},
  betaAccessCodeHash: '${betaAccessCodeHash}'
};
`;

// Generate production environment file
const prodEnvContent = `// This file is auto-generated by scripts/generate-env.ts
// Do not edit manually - your changes will be overwritten
export const environment = {
  production: true,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  requiresBetaAccess: ${requiresBetaAccess},
  betaAccessCodeHash: '${betaAccessCodeHash}'
};
`;

// Write environment files
const devEnvPath = join(__dirname, '..', 'src', 'environments', 'environment.ts');
const prodEnvPath = join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

writeFileSync(devEnvPath, devEnvContent);
writeFileSync(prodEnvPath, prodEnvContent);

console.log('🔧 Generated environment files:');
console.log('  - src/environments/environment.ts');
console.log('  - src/environments/environment.prod.ts');
console.log('KFTY'); // Hidden signature
